#!/usr/bin/env python
# -*- coding: utf-8 -*-

single_letter_aa = list('ACDEFGHIKLMNPQRSTVWY-')

three_letter_aa = ["ALA", "CYS", "ASP", "GLU", "PHE", "GLY", "HIS", "ILE",
                   "LYS", "LEU", "MET", "ASN", "PRO", "GLN", "ARG", "SER",
                   "THR", "VAL", "TRP", "TYR", "-"]

three_to_single_aa = dict(zip(three_letter_aa, single_letter_aa))

# taken from http://www.ensembl.org/info/about/species.html
# on 10.08.2015
valid_ensembl_species = ['orycteropus_afer_afer',
                         'vicugna_pacos',
                         'poecilia_formosa',
                         'anolis_carolinensis',
                         'dasypus_novemcinctus',
                         'melopsittacus_undulatus',
                         'otolemur_garnettii',
                         'ciona_intestinalis',
                         'ciona_savignyi',
                         'caenorhabditis_elegans',
                         'felis_catus',
                         'astyanax_mexicanus',
                         'gallus_gallus',
                         'pan_troglodytes',
                         'pan_troglodytes',
                         'cricetulus_griseus',
                         'pelodiscus_sinensis',
                         'gadus_morhua',
                         'latimeria_chalumnae',
                         'bos_taurus',
                         'macaca_fascicularis',
                         'canis_lupus_familiaris',
                         'tursiops_truncatus',
                         'tursiops_truncatus',
                         'anas_platyrhynchos',
                         'loxodonta_africana',
                         'mustela_putorius_furo',
                         'ficedula_albicollis',
                         'drosophila_melanogaster',
                         'takifugu_rubripes',
                         'takifugu_rubripes',
                         'nomascus_leucogenys',
                         'gorilla_gorilla_gorilla',
                         'cavia_porcellus',
                         'papio_hamadryas',
                         'erinaceus_europaeus',
                         'erinaceus_europaeus',
                         'equus_caballus',
                         'homo_sapiens', 'human',
                         'procavia_capensis',
                         'dipodomys_ordii',
                         'petromyzon_marinus',
                         'echinops_telfairi',
                         'macaca_mulatta',
                         'callithrix_jacchus',
                         'oryzias_latipes',
                         'pteropus_vampyrus',
                         'myotis_lucifugus',
                         'mus_musculus',
                         'microcebus_murinus',
                         'heterocephalus_glaber',
                         'papio_anubis',
                         'monodelphis_domestica',
                         'pongo_abelii',
                         'chrysemys_picta_bellii',
                         'ailuropoda_melanoleuca',
                         'sus_scrofa',
                         'sus_scrofa_map',
                         'ochotona_princeps',
                         'ochotona_princeps',
                         'xiphophorus_maculatus',
                         'ornithorhynchus_anatinus',
                         'microtus_ochrogaster',
                         'oryctolagus_cuniculus',
                         'rattus_norvegicus',
                         'ceratotherium_simum_simum',
                         'saccharomyces_cerevisiae',
                         'ovis_aries',
                         'sorex_araneus',
                         'sorex_araneus',
                         'choloepus_hoffmanni',
                         'physter_macrocephalus',
                         'lepisosteus_oculatus',
                         'ictidomys_tridecemlineatus',
                         'saimiri_boliviensis',
                         'gasterosteus_aculeatus',
                         'tarsius_syrichta',
                         'sarcophilus_harrisii',
                         'tetraodon_nigroviridis',
                         'oreochromis_niloticus',
                         'tupaia_belangeri',
                         'meleagris_gallopavo',
                         'chlorocebus_sabaeus',
                         'macropus_eugenii',
                         'xenopus_tropicalis',
                         'taeniopygia_guttata',
                         'danio_rerio']

# taken from http://www.ensembl.org/info/genome/variation/data_description.html
# on 10.08.2015
valid_ensembl_species_variation = ['bos_taurus',
                                   'canis_familiaris',
                                   'danio_rerio',
                                   'drosophila_melanogaster',
                                   'equus_caballus',
                                   'felis_catus',
                                   'gallus_gallus',
                                   'homo_sapiens', 'human',
                                   'macaca_mulatta',
                                   'meleagris_gallopavo',
                                   'monodelphis_domestica',
                                   'mus_musculus',
                                   'nomascus_leucogenys',
                                   'ornithorhynchus_anatinus',
                                   'ovis_aries',
                                   'pan_troglodytes',
                                   'pongo_abelii',
                                   'rattus_norvegicus',
                                   'saccharomyces_cerevisiae',
                                   'tetraodon_nigroviridis']
